### ISSUE TITLE
Why `flask-mailman`, `flask-mailing` and `navycut` removed from the resource ?

### ISSUE THREAD

**Issue by marktennyson** [flaskcwg/flaskcwg.github.io#71]
Is there any special reason behind the removing of the `flask-mailman`, `flask-mailing` and `navycut` ?

**Comment by Abdur-rahmaanJ** [comment]
@marktennyson i don't know maybe @Jalkhov did some overriding push?

**Comment by Jalkhov** [comment]
@Abdur-rahmaanJ @marktennyson Checking...

**Comment by Jalkhov** [comment]
@Abdur-rahmaanJ @marktennyson I really don't remember having touched those elements directly, I was checking the commits of the `info.json` file and simply from [THIS](https://github.com/flaskcwg/flaskcwg.github.io/commit/03b72739ef8af3112623330a55c2cec3c00837ee#diff-08b0decf4d53031c464a737d7b2e4dace532bd33cc54ca6c90c7a2f5d18fbb0b) commit which was where it was added to [THIS](https://github.com/flaskcwg/flaskcwg.github.io/commit/54b47c860a53436a40c027b286bc61376634f117#) which is the next one where that file is modified, it disappears, if you notice in the diff it doesn't say that it was removed, I really don't know what could have happened, but well, I'll add them, because if you see even the "mail" section disappeared.

**Comment by Abdur-rahmaanJ** [comment]
Ok, good to know!

**Comment by marktennyson** [comment]
Thanks for fixing this.😊
